
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={catalog:null,latest:null,scores:null,route:'home',sector:null,metric:null,range:'1Y'};
async function j(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(u+' '+r.status);return r.json()}
function fmt(v){if(v==null)return'—';if(Math.abs(v)>=1e6)return(v/1e6).toFixed(1)+'M';if(Math.abs(v)>=1e4)return Math.round(v).toLocaleString();return Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function dc(x){return x>0?'up':x<0?'down':'flat'} function all(){return state.catalog.sectors.flatMap(s=>s.indicators.map(i=>({...i,sectorId:s.id,sectorName:s.name})))} function mb(id){return all().find(i=>i.id===id)} function sb(id){return state.catalog.sectors.find(s=>s.id===id)}
function score(id){const c=state.scores[id];let total=0,w=0;for(const[k,wt]of Object.entries(c.weights)){const x=state.latest.items[k];if(!x)continue;total+=Math.tanh((x.change_pct||0)/3)*wt;w+=Math.abs(wt)}return Math.max(0,Math.min(100,Math.round(50+(w?total/w:0)*40)))} function st(n){return n>=75?'偏强':n>=60?'改善':n>=40?'中性':n>=25?'偏弱':'承压'}
function card(i){const x=state.latest.items[i.id]||{},c=dc(x.change_pct||0),live=x.is_demo===false;return `<div class="card clickable" data-metric="${i.id}"><div class="card-head"><div class="name">${i.name}</div><div class="freq">${live?'LIVE · ':''}${i.frequency}</div></div><div class="value">${fmt(x.value)}<span class="unit">${i.unit}</span></div><div class="delta ${c}">${(x.change_pct||0)>0?'+':''}${fmt(x.change_pct||0)}%</div></div>`}
function home(){const f=['copper_price','gold_price','a_share_turnover','mfg_pmi','bank_pb','sox_index'].map(mb);return `<section class="hero"><div class="hero-row"><div><div class="meta">多行业 · 多指标 · 历史趋势</div><h2>市场研究驾驶舱</h2><p>宏观、行业景气、价格与估值放在一个移动端终端。</p></div><div class="badge">${state.latest.is_demo?'DEMO':'LIVE'}</div></div></section><div class="notice">当前包内历史序列为演示数据，用于验证页面和折线图。接入真实数据源后可直接替换 JSON。</div><div class="section-title"><h3>市场总览</h3><span>点击查看趋势</span></div><div class="grid">${f.map(card).join('')}</div><div class="section-title"><h3>行业景气</h3><span>趋势评分</span></div><div class="list">${state.catalog.sectors.map(s=>{const n=score(s.id);return `<div class="list-item clickable" data-sector="${s.id}"><div class="sector-card"><div class="sector-icon">${s.icon}</div><div><h4>${s.name}</h4><p>${s.description}</p></div></div><div class="score"><strong>${n}</strong><small>${st(n)}</small></div></div>`}).join('')}</div>`}
function sectors(){return `<div class="section-title"><h3>行业板块</h3><span>6 个板块</span></div><div class="list">${state.catalog.sectors.map(s=>{const n=score(s.id);return `<div class="list-item clickable" data-sector="${s.id}"><div class="sector-card"><div class="sector-icon">${s.icon}</div><div><h4>${s.name}</h4><p>${s.indicators.length} 个指标 · ${s.description}</p></div></div><div class="score"><strong>${n}</strong><small>${st(n)}</small></div></div>`}).join('')}</div>`}
function sector(id){const s=sb(id),n=score(id);return `<button class="back" data-back="sectors">← 返回行业</button><section class="hero"><div class="hero-row"><div><div class="meta">${s.icon} ${s.name}</div><h2>${state.scores[id].label}</h2><p>${s.description}</p></div><div><div class="big-score">${n}</div><div class="meta">${st(n)}</div></div></div><div class="scorebar"><div style="width:${n}%"></div></div></section><div class="section-title"><h3>关键指标</h3><span>${s.indicators.length} 项</span></div><div class="grid">${s.indicators.map(card).join('')}</div>`}
function market(){const groups=[['有色行情',['copper_price','aluminum_price','gold_price','silver_price','zinc_price','nickel_price']],['权益市场',['csi300','csi1000','sox_index']],['利率与汇率',['dxy','us_real_yield_10y','china_10y_yield']]];return groups.map(g=>`<div class="section-title"><h3>${g[0]}</h3><span>行情</span></div><div class="grid">${g[1].map(mb).map(card).join('')}</div>`).join('')}
function rows(a){return a.map(i=>{const x=state.latest.items[i.id]||{};return `<div class="list-item clickable" data-metric="${i.id}"><div><div>${i.name}</div><small>${i.sectorName} · ${i.frequency}</small></div><div style="text-align:right"><strong>${fmt(x.value)} ${i.unit}</strong><small class="${dc(x.change_pct||0)}">${(x.change_pct||0)>0?'+':''}${fmt(x.change_pct||0)}%</small></div></div>`}).join('')}
function data(){return `<input id="searchBox" class="search" placeholder="搜索指标，例如：PMI、铜、ROE、半导体…"><div class="section-title"><h3>全部指标</h3><span>${all().length} 项</span></div><div id="dataList" class="list">${rows(all())}</div>`}
function about(){return `<section class="hero"><div class="meta">VERSION 3.0.0</div><h2>投资研究终端</h2><p>移动端 PWA / Android TWA 前端。</p></section><div class="notice">${state.catalog.disclaimer}</div><div class="list"><div class="list-item"><div>板块</div><small>有色 / 银行 / 券商 / 医药 / 制造 / 科技</small></div><div class="list-item"><div>图表</div><small>原生 Canvas，无第三方 CDN</small></div></div>`}
function fr(data,r){const n={'1M':30,'3M':90,'1Y':365,'3Y':1095,'5Y':1825,'ALL':999999}[r];return data.length>n?data.slice(-n):data}
async function metric(id){const i=mb(id),h=await j(`./data/history/${id}.json`),a=fr(h.data,state.range),v=a.map(x=>+x[1]),cur=v.at(-1),mn=Math.min(...v),mx=Math.max(...v),p=v[0]?((cur-v[0])/Math.abs(v[0])*100):0;$('#view').innerHTML=`<button class="back" data-back="${state.sector?'sector':'home'}">← 返回</button><div class="detail-title"><div><div class="meta">${i.sectorName} · ${i.frequency}</div><h2>${i.name}</h2></div><div class="detail-current"><strong>${fmt(cur)}</strong><span class="unit">${i.unit}</span><div class="meta">${h.updated}</div></div></div><div class="range-row">${['1M','3M','1Y','3Y','5Y','ALL'].map(r=>`<button class="${state.range===r?'active':''}" data-range="${r}">${r}</button>`).join('')}</div><div class="chart-wrap"><canvas id="chart"></canvas></div><div class="stat-row"><div class="stat"><span>区间涨跌</span><strong class="${dc(p)}">${p>0?'+':''}${p.toFixed(2)}%</strong></div><div class="stat"><span>区间最低</span><strong>${fmt(mn)}</strong></div><div class="stat"><span>区间最高</span><strong>${fmt(mx)}</strong></div></div>${h.is_demo?'<div class="notice">该指标当前为 DEMO 数据。替换对应 history JSON 后图表会自动读取真实序列。</div>':'<div class="notice" style="border-color:#1f5a43;background:#10271e;color:#8ee6b4">LIVE 数据 · 来源：'+h.source+' · 最新观测：'+h.updated+'</div>'}`;draw($('#chart'),a);bind()}
function draw(c,d){const r=c.getBoundingClientRect(),q=devicePixelRatio||1;c.width=r.width*q;c.height=r.height*q;const x=c.getContext('2d');x.scale(q,q);const w=r.width,h=r.height,p={l:45,r:12,t:14,b:28},v=d.map(z=>+z[1]);let mn=Math.min(...v),mx=Math.max(...v);if(mx===mn){mx++;mn--}const pad=(mx-mn)*.08;mn-=pad;mx+=pad;const X=i=>p.l+(w-p.l-p.r)*i/(v.length-1),Y=z=>p.t+(h-p.t-p.b)*(1-(z-mn)/(mx-mn));x.strokeStyle='#20324b';x.fillStyle='#8ea5bf';x.font='10px sans-serif';for(let i=0;i<4;i++){const y=p.t+(h-p.t-p.b)*i/3;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillText(fmt(mx-(mx-mn)*i/3),4,y+3)}x.strokeStyle='#5dd6ff';x.lineWidth=2;x.beginPath();v.forEach((z,i)=>i?x.lineTo(X(i),Y(z)):x.moveTo(X(i),Y(z)));x.stroke()}
function bind(){$$('[data-metric]').forEach(e=>e.onclick=()=>{state.metric=e.dataset.metric;metric(state.metric)});$$('[data-sector]').forEach(e=>e.onclick=()=>{state.sector=e.dataset.sector;state.route='sector';render()});$$('[data-back]').forEach(e=>e.onclick=()=>{const b=e.dataset.back;if(b==='sector')state.route='sector';else{state.route=b;state.sector=null}render()});$$('[data-range]').forEach(e=>e.onclick=()=>{state.range=e.dataset.range;metric(state.metric)});const s=$('#searchBox');if(s)s.oninput=()=>{$('#dataList').innerHTML=rows(all().filter(i=>(i.name+i.sectorName+i.id).toLowerCase().includes(s.value.trim().toLowerCase())));bind()}}
function render(){const v=$('#view');if(state.route==='home')v.innerHTML=home();if(state.route==='sectors')v.innerHTML=sectors();if(state.route==='sector')v.innerHTML=sector(state.sector);if(state.route==='market')v.innerHTML=market();if(state.route==='data')v.innerHTML=data();if(state.route==='about')v.innerHTML=about();$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route||(state.route==='sector'&&b.dataset.route==='sectors')));bind()}
async function boot(){[state.catalog,state.latest,state.scores]=await Promise.all([j('./data/catalog.json'),j('./data/latest.json'),j('./data/score_config.json')]);render()}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;state.sector=null;render()});$('#refreshBtn').onclick=async()=>{state.latest=await j('./data/latest.json');render()};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));boot();
